{% set name = "eagerpy" %}
{% set version = "0.29.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bd9cb9170dcb9eeb25b6fd90c827c665322f4e78b12ce845b93052f04d3a9408

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - python >={{ python_min }}
    - typing-extensions >=3.7.4.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - eagerpy
    - eagerpy.tensor

about:
  home: https://eagerpy.jonasrauber.de/
  license: MIT
  license_family: MIT
  license_file: LICENSE # PR here: https://github.com/jonasrauber/eagerpy/pull/7
  summary: EagerPy is a thin wrapper around PyTorch, TensorFlow Eager, JAX and NumPy that unifies their interface and thus allows writing code that works natively across all of them.
  doc_url: https://eagerpy.jonasrauber.de/
  dev_url: https://github.com/jonasrauber/eagerpy

extra:
  recipe-maintainers:
    - ndmaxar
    - oblute
    - rluria14
